language: java
jdk: oraclejdk8
deploy:
  provider: heroku
  app: achievement-api-remembranza
  api_key:
    secure: ahbs15nspR9BVPeY6X05sFTeLYkLgR8l0ngIaXN3J58/WVq4mCgZagAom4v0uWivtRjCwID6wE+0PG/Zy8XjvN1YLxl6A3HryYLxy6tUsJXe7RfpxzQvyu+WdeCFKuPF48lIreTUZUGkQVR0ZoZoquMIy2ItvN9EFnm/38suGlOHXIXJek5gvWbmq7bhJFMH/qSPOXRBWzhL9zcZVdfq2Jz+HtmLIp1UyNOuZqofrzw/5eJvILyDWGmXpsvVDDfiQY4BkzHIOmxPYB9n2soav0qqF6DiForxXnpzWR53N8fO1vTjS+jrZbEnZ3pGJMEL4lalhNi7hiPH3KAr6Tbo/2cEr4RIuXL7uv5Jjzx219KWt1aeIZFk8+uah55aoHIHViLaPa/MuubjwRQ9PJgdN+qYtf/iAArzgSpVS5UFQDybFGQQVJThwJY0Ieu1o3OYycjx6F/EA2MDVynN7zNIP884yc7i9C20k2mEkE1JYtwTIZFgGGoG75uz3rB5ydNQM6/DwiQDr610BsNmVMB4EM4HlfpSupWeFaLwwirjm1ehMkvIhssBWSdhxjcakvULqvVfL5NUBstwP1zGmsQg8TzxJRRsM0Qc+LQk2m0oVoDtS8bp8+ygvw7JWBFPUizbCXaHKKFxTqPKFsZhnLWusf6KdyS8hRfoxQaxZZzkLME=
